project:
  type: website
  output-dir: docs

website:
  title: "Angel Leon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aleonxv/R_myfinancialproject
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-leon-25124720a/
format:
  html:
    theme: lux
    css: styles.css

editor: visual

